# Generated by Django 5.1.6 on 2025-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inventoryitem_options_inventoryitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'In Stock'), (2, 'Low Stock'), (1, 'Out of Stock'), (0, 'Unknown')], default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
