# Generated by Django 5.1.5 on 2025-03-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_changelog'),
        ('core', '0005_remove_inventoryitem_supplier'),
    ]

    operations = [
    ]
