# Generated by Django 5.1.6 on 2025-03-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_expected_delivery_order_product_order_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
