# Generated by Django 5.1.6 on 2025-03-31 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_notification'),
        ('core', '0008_order_expected_delivery_alter_profile_role'),
    ]

    operations = [
    ]
