# Generated by Django 5.1.6 on 2025-04-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_expected_delivery_alter_profile_role'),
    ]

    operations = [
    ]
