# Generated by Django 5.1.5 on 2025-04-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_expected_delivery_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='alert_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
