# Generated by Django 5.1.5 on 2025-04-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20250330_1714'),
        ('core', '0008_order_expected_delivery_alter_profile_role'),
    ]

    operations = [
    ]
