# Generated by Django 5.1.5 on 2025-04-03 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20250402_2022'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=255, null=True)),
                ('new_value', models.CharField(max_length=255, null=True)),
                ('date_executed', models.DateTimeField(auto_now_add=True)),
                ('executing_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventoryitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
