# Generated by Django 5.1.5 on 2025-04-05 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inventoryitemchanges_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitemchanges',
            name='field_name',
        ),
        migrations.AddField(
            model_name='inventoryitemchanges',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(3, 'In Stock'), (2, 'Low Stock'), (1, 'Out of Stock'), (0, 'Unknown')], default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitemchanges',
            name='executing_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
