# Generated by Django 5.1.6 on 2025-04-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_inventoryitemchanges_field_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryitemchanges",
            options={"ordering": ["-date_executed"]},
        ),
    ]
