# Generated by Django 5.1.5 on 2025-04-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventoryitem_alert_triggered_delete_notification'),
        ('core', '0011_remove_inventoryitemchanges_field_name_and_more'),
    ]

    operations = [
    ]
