# Generated by Django 5.1.5 on 2025-04-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20250414_1807'),
        ('core', '0012_remove_inventoryitem_description_and_more'),
    ]

    operations = [
    ]
